# Generated by Django 5.0.6 on 2024-07-03 10:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(5)])),
                ('email_id', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('company_code', models.CharField(blank=True, max_length=5, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[A-Za-z]{2}\\d{2}[EN]$')])),
                ('strength', models.PositiveIntegerField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()])),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
